  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - quarkus-lambda-blog-rest-1.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL

  Resources:
    QuarkusLambdaBlogRest:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: target/function.zip
        MemorySize: 2048
        Policies:
          - AWSLambdaBasicExecutionRole
          - DynamoDBCrudPolicy:
              TableName: !Ref PostDDBTable
          - DynamoDBCrudPolicy:
              TableName: !Ref TagDDBTable
          - DynamoDBCrudPolicy:
              TableName: !Ref PostTagDDBTable

        Timeout: 150
        Events:
          GetResource:
            Type: Api
            Properties:
              Path: /blog/{proxy+}
              Method: any

    PostDDBTable:
      Type: AWS::Serverless::SimpleTable
      Properties:
        TableName: Post
        PrimaryKey:
          Name: id
          Type: String

    TagDDBTable:
      Type: AWS::Serverless::SimpleTable
      Properties:
        TableName: Tag
        PrimaryKey:
          Name: id
          Type: String

    PostTagDDBTable:
      Type: AWS::Serverless::SimpleTable
      Properties:
        TableName: PostTag
#        PrimaryKey:
#          Name: id
#          Type: String

  Outputs:
    QuarkusLambdaBlogRestApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
      Export:
        Name: QuarkusLambdaBlogRestApi
